container:
  image: cirrusci/android-sdk:28
  cpu: 1
  memory: 8G

task:
  name: debug-build

  script: |
    ./gradlew assembleDebug

  output_artifacts:
    path: "./app/build/outputs/apk/debug/*.apk"
